### ISSUE TITLE
Get Service details is broken

### ISSUE THREAD

**Issue by davidglvn** [fastly/fastly-py#86]
Hi,
I'm trying to run `get_service_detail` function and receiving an error both with using service version and without it:
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1784, in get_allof_instances
    allof_instance = allof_class._from_openapi_data(**model_args, **constant_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/version_detail.py", line 239, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 184, in __setattr__
    self[attr] = value
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 509, in __setitem__
    self.set_attribute(name, value)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 156, in set_attribute
    value = validate_and_convert_types(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1619, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1569, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1453, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1373, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 369, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/header_response.py", line 245, in _from_openapi_data
    composed_info = validate_get_composed_info(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1992, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1780, in get_allof_instances
    for allof_class in self._composed_schemas['allOf']:
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 62, in __get__
    result = self._fn()
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/header_response.py", line 387, in _composed_schemas
    lazy_import()
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/header_response.py", line 35, in lazy_import
    from fastly.model.str_none_type import StrNoneType
ModuleNotFoundError: No module named 'fastly.model.str_none_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1784, in get_allof_instances
    allof_instance = allof_class._from_openapi_data(**model_args, **constant_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/service_detail_all_of.py", line 181, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 184, in __setattr__
    self[attr] = value
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 509, in __setitem__
    self.set_attribute(name, value)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 156, in set_attribute
    value = validate_and_convert_types(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1569, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1462, in attempt_convert_item
    raise conversion_exc
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1453, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1373, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 369, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/service_version_detail.py", line 279, in _from_openapi_data
    composed_info = validate_get_composed_info(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1992, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1789, in get_allof_instances
    raise ApiValueError(
fastly.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'VersionDetail'. The input data was invalid for the allOf schema 'VersionDetail' in the composed schema 'ServiceVersionDetail'. Error=No module named 'fastly.model.str_none_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/davidg/Code/devops/lambdas/fastly/main.py", line 126, in <module>
    api_response = api_instance.get_service_detail(service_id)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/api/service_api.py", line 830, in get_service_detail
    return self.get_service_detail_endpoint.call_with_http_info(**kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/api_client.py", line 862, in call_with_http_info
    return self.api_client.call_api(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/api_client.py", line 421, in call_api
    return self.__call_api(resource_path, method,
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/api_client.py", line 232, in __call_api
    return_data = self.deserialize(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/api_client.py", line 337, in deserialize
    deserialized_data = validate_and_convert_types(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1569, in validate_and_convert_types
    converted_instance = attempt_convert_item(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1462, in attempt_convert_item
    raise conversion_exc
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1453, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1373, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 369, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model/service_detail.py", line 226, in _from_openapi_data
    composed_info = validate_get_composed_info(
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1992, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
  File "/opt/homebrew/lib/python3.9/site-packages/fastly/model_utils.py", line 1789, in get_allof_instances
    raise ApiValueError(
fastly.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'ServiceDetailAllOf'. The input data was invalid for the allOf schema 'ServiceDetailAllOf' in the composed schema 'ServiceDetail'. Error=Invalid inputs given to generate an instance of 'VersionDetail'. The input data was invalid for the allOf schema 'VersionDetail' in the composed schema 'ServiceVersionDetail'. Error=No module named 'fastly.model.str_none_type'
```

The code is the example code in [get_service_detail](https://github.com/fastly/fastly-py/blob/main/docs/ServiceApi.md#get_service_detail) with correct api key and service id and using latest 1.1.0 version.

From debbugin it looks like this module is really not exists in the code: https://github.com/fastly/fastly-py/blob/ffef2b7bc453660fad99ecfcd87bb7200d177813/fastly/model/header_response.py#L35

**Comment by davidglvn** [comment]
I've commented out `StrNoneType` import and got new error that priority in headers is expected to be integer and it's sent as string in the response...
```
Required value type is int and passed type was str at ['received_data']['version']['headers'][0]['priority']
```

**Comment by Integralist** [comment]
Hi @davidglvn 👋🏻  

Thanks for raising this issue. 

We have an internal ticket now tracking this issue and we'll report back once we have an update.

**Comment by Integralist** [comment]
👋🏻 

It looks like this was resolved in one of the recent releases as I was able to get this to work using the latest `3.0.0` release.
