### ISSUE TITLE
'fastly is not a package' on macos with python 3.11

### ISSUE THREAD

**Issue by benbradford** [fastly/fastly-py#91]
```
➜  fastly python3 -m pip install fastly
Requirement already satisfied: fastly in /usr/local/lib/python3.11/site-packages (2.2.1)
➜  fastly python3
Python 3.11.2 (main, Mar 24 2023, 00:31:37) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<redacted>/fastly.py", line 2, in <module>
    from fastly.api import tokens_api
ModuleNotFoundError: No module named 'fastly.api'; 'fastly' is not a package
>>>
```

**Comment by benbradford** [comment]
Fixed with

```
!pip install xformers clip open_clip_torch blendmodes accelerate basicsr fonts font-roboto gfpgan gradio==3.16.2 invisible-watermark numpy omegaconf opencv-contrib-python requests piexif Pillow pytorch_lightning==1.7.7 realesrgan scikit-image>=0.19 timm==0.4.12 transformers==4.25.1 torch einops jsonmerge clean-fid resize-right torchdiffeq kornia lark inflection GitPython torchsde safetensors psutil

!pip install --upgrade fastapi==0.90.1
```
