### ISSUE TITLE
CustomerApi list_users doesn't like require_new_password being null

### ISSUE THREAD

**Issue by pnickerson-cashstar** [fastly/fastly-py#92]
**Version**

Python 3.11.3
fastly 2.3.0

**What happened**

Tried following each of these CustomerApi list_users examples:
https://developer.fastly.com/reference/api/account/customer/#list-users
https://github.com/fastly/fastly-py/blob/main/docs/CustomerApi.md#list_users

With both, I get this error:
```
Traceback (most recent call last):
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1784, in get_allof_instances
    allof_instance = allof_class._from_openapi_data(**model_args, **constant_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model/user.py", line 198, in _from_openapi_data
    setattr(self, var_name, var_value)
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 184, in __setattr__
    self[attr] = value
    ~~~~^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 509, in __setitem__
    self.set_attribute(name, value)
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 156, in set_attribute
    value = validate_and_convert_types(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1569, in validate_and_convert_types
    converted_instance = attempt_convert_item(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1448, in attempt_convert_item
    raise get_type_error(input_value, path_to_item, valid_classes,
fastly.exceptions.ApiTypeError: Invalid type for variable 'require_new_password'. Required value type is bool and passed type was NoneType at ['received_data'][0]['require_new_password']

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pnickerson/repositories/devops_shared/cashstar/./uar-fastly.py", line 32, in <module>
    api_response = api_instance.list_users(customer_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/api/customer_api.py", line 762, in list_users
    return self.list_users_endpoint.call_with_http_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/api_client.py", line 872, in call_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/api_client.py", line 427, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/api_client.py", line 236, in __call_api
    return_data = self.deserialize(
                  ^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/api_client.py", line 341, in deserialize
    deserialized_data = validate_and_convert_types(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1619, in validate_and_convert_types
    input_value[index] = validate_and_convert_types(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1569, in validate_and_convert_types
    converted_instance = attempt_convert_item(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1462, in attempt_convert_item
    raise conversion_exc
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1453, in attempt_convert_item
    return deserialize_model(input_value, valid_class,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1373, in deserialize_model
    return model_class._new_from_openapi_data(**kw_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 369, in _new_from_openapi_data
    return cls._from_openapi_data(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 45, in wrapped_init
    return fn(_self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model/schemas_user_response.py", line 226, in _from_openapi_data
    composed_info = validate_get_composed_info(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1992, in validate_get_composed_info
    allof_instances = get_allof_instances(self, model_args, constant_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pnickerson/.local/lib/python3.11/site-packages/fastly/model_utils.py", line 1789, in get_allof_instances
    raise ApiValueError(
fastly.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'User'. The input data was invalid for the allOf schema 'User' in the composed schema 'SchemasUserResponse'. Error=Invalid type for variable 'require_new_password'. Required value type is bool and passed type was NoneType at ['received_data'][0]['require_new_password']
```
If I use curl against the API, I notice the result includes this key-value pair:
`[{"require_new_password": null,...},...]`

**Comment by Integralist** [comment]
👋🏻 

I've now fixed this issue and will get it out into a new release shortly.
